### ISSUE TITLE
Copy and Paste License Keys

### ISSUE THREAD

**Issue by TheJediNinja** [codesnippetspro/code-snippets#142]
This is more of a Freemius issue (hopefully can remove Freemius in the near future ;) - When copy and pasting the license key to a doc or 3rd party management system (I'm using Notion), and then copy and paste from there, an error shows saying there needs to be 32 characters. I found the license key can only be copied and pasted from the CodeSnippets dashboard to work.

**Comment by sheabunge** [comment]
Hi @TheJediNinja,

Is it possible that when pasting the key from a different source, you are getting some whitespace added to the beginning or end of the license key, making it slightly longer than it should be?

I'll pass this on to our contact at Freemius to see whether it can be addressed in the SDK.

**Comment by sheabunge** [comment]
Closing this for now. Please reopen if you have any further occurrences or information that might help us fix.
