### ISSUE TITLE
Database errors on the fresh installation of the plugin

### ISSUE THREAD

**Issue by nirbhay18** [codesnippetspro/code-snippets#144]
**Environment:**Local by Flywhell

[https://www.loom.com/share/a40972e84997463da5dd9f0e0b8ea752
](https://www.loom.com/share/a40972e84997463da5dd9f0e0b8ea752
)

![image](https://user-images.githubusercontent.com/2735045/186960035-16f7576a-0a28-46fb-9c3b-fe5208c2d938.png)

**Comment by sheabunge** [comment]
I believe this is an expected quirk in how the WordPress `dbDelta` function works.
