### ISSUE TITLE
Code formatter ( prettier / beautifier )

### ISSUE THREAD

**Issue by wiryonolau** [codesnippetspro/code-snippets#145]
Any plan to implement code prettier / beautifier. I have to paste the code back and forth to vscode just to format the code

**Comment by luizbills** [comment]
Press `SHIFT + TAB`

**Comment by mjdewitt** [comment]
Who knew? Delighted to have this. 

It would be great to document the feature under the "?" hot-key help.

**Comment by sheabunge** [comment]
Thanks all for the suggestions and advice!
