### ISSUE TITLE
PHP warning error

### ISSUE THREAD

**Issue by Briannewhall** [codesnippetspro/code-snippets#158]
after upgrading to PHP 8.1 this warning appeared

Warning: Undefined variable $rw in /var/web/site/public_html/wp-content/plugins/code-snippets-pro/php/snippet-ops.php(511) : eval()'d code on line 46

Warning: Attempt to read property "ID" on null in /var/web/site/public_html/wp-content/plugins/code-snippets-pro/php/snippet-ops.php(511) : eval()'d code on line 46

**Comment by sheabunge** [comment]
This is an error coming from one of your snippets. You're trying to read a property from an undefined variable.

Happy to help debug your code if you post here, but it's not an issue with the plugin itself.
