### ISSUE TITLE
WP Multisite - Network Activation 

### ISSUE THREAD

**Issue by onemcogit** [codesnippetspro/code-snippets#162]
If I network activate the plugin, snippets only appears in network dashboard and main website dashboard but does not appear in child websites. 

But if I disable network activate,  I am able to then individually enable it on each child sites.

**Comment by sheabunge** [comment]
You'll need to enable this option on the Network Settings page to enable menus on child sites.

![image](https://github.com/codesnippetspro/code-snippets/assets/1170783/f9127a71-99ca-4bea-941b-e53674b2aa00)

You can find more info here: https://help.codesnippets.pro/article/53-does-code-snippets-work-on-wordpress-multisite
